name: Eleventy Build

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
      - '!gh-pages'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '16.x'

        - run: npm install

        - run: npm run build
